repos:
  - repo: https://github.com/prettier/prettier
    rev: ""
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
